config/routes.rb
Rails.application.routes.draw do
  get 'trends/index'
  get 'trends/trend_by_category'
  resources :otypes
  get 'reports/index'
  get 'reports/report_by_category'
  get 'reports/report_by_dates'
  get 'main/index'
  resources :operations
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#index"
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @top3ops = Operation.select(:id, :description, :amount, :odate).last_month.top_x(3).type_is(2)
    @profit_last_month = Operation.last_month.type_is(1).sum(:amount)
    @expenses_last_month = Operation.last_month.type_is(2).sum(:amount)
    @most_expensive_category = Operation.joins(:category).last_month.type_is(2).group(:name).sum(:amount).max_by{ |k,v| v }
    
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_operation.html.erb
<li class = "mb-3"><mark><b><%= operation.amount %></b></mark><a class="text-decoration-none" href="<%= operation_url(:id => operation.id) %>"> <%= operation.description %></a> <small>(<%= l(operation.odate, format: '%d %B') %>)</small></li>

app/views/main/index.html.erb
<div class="row align-items-md-stretch mb-4">
  <div class="col-md-6">
    <div class="h-100 p-5 bg-light border rounded-3">
      <h2 class="text-danger"><%= @expenses_last_month %></h2>
      <p>Ваші витрати за минулий місяць</p>
      <a href="<%= operations_path(@operation, :otype_id => "2") %>" class="btn btn-outline-primary" role="button"><%= t('label_all') + ' ' + t('report_generator.expenses', :count => 2).downcase %></a>
    </div>
  </div>
  <div class="col-md-6">
    <div class="h-100 p-5 bg-light border rounded-3">
      <h2 class="text-success"><%= @profit_last_month %></h2>
      <p>Ваші доходи за минулий місяць</p>
      <a href="<%= operations_path(@operation, :otype_id => "1") %>" class="btn btn-outline-primary" role="button"><%= t('label_all') + ' ' + t('report_generator.profits', :count => 2).downcase %></a>
    </div>
  </div>
</div>
<div class="p-5 mb-4 bg-light border rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold"><%= @most_expensive_category[0] %></h1>
    <div class="col-md-10 fs-4">
        <p>найбільш витратна категорія минулого місяця, на неї було витрачено <strong><mark><%= @most_expensive_category[1] %></mark></strong> грн</p>
    </div>
    <a href="<%= reports_index_path %>" class="btn btn-lg btn-outline-primary mt-3" role="button"><%= t('report_generator.title') %></a>
  </div>
</div>
<div class="p-5 mb-4 bg-light border rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">TOP 3 витрат за минулий місяць</h1>
    <div class="col-md-10 fs-4">
        <ol>
            <%= render partial: "operation", collection: @top3ops %>
        </ol>        
    </div>
    <a href="<%= trends_trend_by_category_path %>" class="btn btn-lg btn-outline-primary mt-3" role="button"><%= t('report_generator.button_see_trends') %></a>
  </div>
</div>