config/routes.rb
Rails.application.routes.draw do
  get 'trends/index'
  get 'trends/trend_by_category'
  resources :otypes
  get 'reports/index'
  get 'reports/report_by_category'
  get 'reports/report_by_dates'
  get 'main/index'
  resources :operations
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#index"
end

app/controllers/otypes_controller.rb
class OtypesController < ApplicationController
  before_action :set_otype, only: %i[ show edit update destroy ]

  # GET /otypes or /otypes.json
  def index
    @otypes = Otype.page(params[:page])
  end

  # GET /otypes/1 or /otypes/1.json
  def show
  end

  # GET /otypes/new
  def new
    @otype = Otype.new
  end

  # GET /otypes/1/edit
  def edit
  end

  # POST /otypes or /otypes.json
  def create
    @otype = Otype.new(otype_params)

    respond_to do |format|
      if @otype.save
        format.html { redirect_to otype_url(@otype), notice: "Тип транзакцій успішно створено." }
        format.json { render :show, status: :created, location: @otype }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @otype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /otypes/1 or /otypes/1.json
  def update
    respond_to do |format|
      if @otype.update(otype_params)
        format.html { redirect_to otype_url(@otype), notice: "Тип транзакцій успішно оновлено." }
        format.json { render :show, status: :ok, location: @otype }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @otype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /otypes/1 or /otypes/1.json
  def destroy
    @otype.destroy

    respond_to do |format|
      format.html { redirect_to otypes_url, notice: "Тип транзакцій успішно видалено." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_otype
      @otype = Otype.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def otype_params
      params.require(:otype).permit(:title)
    end
end

app/helpers/otypes_helper.rb
module OtypesHelper
end

app/views/otypes/_form.html.erb
<%= form_with(model: otype) do |form| %>
  <% if otype.errors.any? %>
    <div style="color: red">
      <h2><%= t('activerecord.errors.template.header', :model => Otype.model_name.human, :count => @otype.errors.count) %></h2>
      <ul>
        <% otype.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, style: "display: block", class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/otypes/_otype.html.erb
<tr id="<%= dom_id otype %>">
      <th scope="row"><%= otype.id %></th>
      <td><%= otype.title %></td>
      <td>
        <div class="d-flex justify-content-around">
          <%= link_to "", edit_otype_path(otype), class: "btn btn-secondary btn-sm bi bi-pencil-square", role: "button", alt: "Edit"  %>
          <%= button_to "", otype, method: :delete, class: "btn btn-danger btn-sm bi bi-x-square", alt: "Delete" %>
        </div>        
      </td>
</tr>

app/views/otypes/edit.html.erb
<h1><%= t('button_edit') + ' ' + Otype.model_name.human %></h1>
<%= render "form", otype: @otype %>

<br>

<div>
  <%= link_to Otype.model_name.human + ' ' + @otype.title, @otype %> |
  <%= link_to t('label_all') + ' ' + Otype.model_name.human(:count => 2), otypes_path %>
</div>

app/views/otypes/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal"><%= Otype.model_name.human(:count => 2) %></h1>
    </div>
  </div>
  <div class="row">
    <div class="p-3 pb-md-4 mx-auto ">
      <%= link_to ' ' +   t('button_add') + ' ' +  Otype.model_name.human, new_otype_path, class: "btn btn-success bi bi-plus-square", role: "button", alt: "Add new"  %>
    </div>
  </div>
  <div class="row">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col"><%= t('activerecord.attributes.otype.title') %></th>
          <th scope="col"><%= t('button_configure') %></th>
        </tr>
      </thead>
      <tbody>
        <% @otypes.each do |otype| %>
          <%= render otype %>
        <% end %>
      </tbody>
    </table>
    <%= paginate @otypes %>
  </div>

</div>

app/views/otypes/new.html.erb
<h1><%= t('button_add') + ' ' + Otype.model_name.human %></h1>

<%= render "form", otype: @otype %>

<br>

<div>
  <%= link_to t('label_all') + ' ' + Category.model_name.human(:count => 2), categories_path %>
</div>

app/views/otypes/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal"><%= @otype.title %></h1>
    </div>
  </div>
  <div class="row">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col"><%= t("activerecord.attributes.otype.title") %></th>
          <th scope="col"><%= t('button_configure') %></th>
        </tr>
      </thead>
      <tbody>
          <%= render @otype %>
      </tbody>
    </table>
  </div>

</div>