config/routes.rb
Rails.application.routes.draw do
  get 'trends/index'
  get 'trends/trend_by_category'
  resources :otypes
  get 'reports/index'
  get 'reports/report_by_category'
  get 'reports/report_by_dates'
  get 'main/index'
  resources :operations
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#index"
end

app/views/shared/_footer.html.erb
  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="/logo_s.png" alt="" >
        <small class="d-block mb-3 text-muted">&copy; 2023</small>
      </div>
      <div class="col-6 col-md">
        <h5><%= Operation.model_name.human(:count => 2) %></h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="<%= operations_url %>"> <%= t('label_all') %></a></li>   
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="<%= operations_path(@operation, :otype_id => "2") %>"><%= t('report_generator.expenses', :count => 2) %></a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="<%= operations_path(@operation, :otype_id => "1") %>"><%= t('report_generator.profits', :count => 2) %></a></li>
          <li class="mb-1"><a class="link-dark  text-decoration-none" href="<%= reports_index_path %>"><%= t('report_generator.title') %></a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>За категоріями</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="<%= reports_report_by_category_path(:otype_id => "2", :start_date => Date.today - 30, :end_date => Date.today) %>"><%= t('report_generator.expenses', :count => 2) %> за 30 днів</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="<%= reports_report_by_category_path(:otype_id => "2", :start_date => Date.today - 7, :end_date => Date.today) %>"><%= t('report_generator.expenses', :count => 2) %> за 7 днів</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="<%= reports_report_by_category_path(:otype_id => "1", :start_date => Date.today - 30, :end_date => Date.today) %>"><%= t('report_generator.profits', :count => 2) %> за 30 днів</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="<%= reports_report_by_category_path(:otype_id => "1", :start_date => Date.today - 7, :end_date => Date.today) %>"><%= t('report_generator.profits', :count => 2) %> за 7 днів</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>По датам</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="<%= reports_report_by_dates_path(:otype_id => "2", :start_date => Date.today - 30, :end_date => Date.today) %>"><%= t('report_generator.expenses', :count => 2) %> за 30 днів</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="<%= reports_report_by_dates_path(:otype_id => "2", :start_date => Date.today - 7, :end_date => Date.today) %>"><%= t('report_generator.expenses', :count => 2) %> за 7 днів</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="<%= reports_report_by_dates_path(:otype_id => "1", :start_date => Date.today - 30, :end_date => Date.today) %>"><%= t('report_generator.profits', :count => 2) %> за 30 днів</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="<%= reports_report_by_dates_path(:otype_id => "1", :start_date => Date.today - 7, :end_date => Date.today) %>"><%= t('report_generator.profits', :count => 2) %> за 7 днів</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Тренди</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="<%= trends_trend_by_category_path %>">По місяцям</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="<%= trends_trend_by_category_path(:period => "week", :ago => "4") %>">По тижням</a></li>
        </ul>
      </div>
    </div>
  </footer>

app/views/shared/_header.html.erb
  <header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <img class="img-fluid" src="/logo.png">
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 text-dark text-decoration-none" href="<%= operations_path %>"><%= Operation.model_name.human(:count => 2) %></a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="<%= categories_path %>"><%= Category.model_name.human(:count => 2) %></a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="<%= reports_index_path %>"><%= t('activemodel.models.reports_controller/report', :count => 2) %></a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="<%= trends_trend_by_category_path %>"><%= t('activemodel.models.trends_controller/trend', :count => 2) %></a>
      </nav>
    </div>
  </header>