config/routes.rb
Rails.application.routes.draw do
  get 'trends/index'
  get 'trends/trend_by_category'
  resources :otypes
  get 'reports/index'
  get 'reports/report_by_category'
  get 'reports/report_by_dates'
  get 'main/index'
  resources :operations
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#index"
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :operations
    validates :name, :description, presence: true
    validates :name, uniqueness: true
    validates :name, :description, length: {maximum: 255}
    paginates_per 10
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.page(params[:page])
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Категорія успішно створена." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Категорія успішно оновлена." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Категорія успішно видалена." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<tr id="<%= dom_id category %>">
      <th scope="row"><%= category.id %></th>
      <td><a href="<%= operations_path(:category_id => category.id) %>"><%= category.name %></a></td>
      <td><%= category.description %></td>
      <td>
        <div class="d-flex justify-content-around">
          <%= link_to "", edit_category_path(category), class: "btn btn-secondary btn-sm bi bi-pencil-square", role: "button", alt: "Edit"  %>
          <%= button_to "", category, method: :delete, class: "btn btn-danger btn-sm bi bi-x-square", alt: "Delete" %>
        </div>        
      </td>
</tr>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= t('activerecord.errors.template.header', :model => Category.model_name.human, :count => @category.errors.count) %></h2>
      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, style: "display: block", class: "form-label" %>
    <%= form.text_field :description, class: "form-control" %>
    <div id="descriptionHelp" class="form-text"><%= t("activerecord.attributes.category.description_help") %></div>
  </div>

  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%=Category.model_name.human + ' / ' + t('button_edit') %></h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to Category.model_name.human + ' ' + @category.description, @category %> |
  <%= link_to t('label_all') + ' ' + Category.model_name.human(:count => 2), categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal"><%= Category.model_name.human(:count => 2) %></h1>
    </div>
  </div>
  <div class="row">
    <div class="p-3 pb-md-4 mx-auto ">
      <%= link_to ' ' + t('helpers.submit.create', :model => Category.model_name.human), new_category_path, class: "btn btn-success bi bi-plus-square", role: "button", alt: "Add new"  %>
    </div>
  </div>
  <div class="row">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col"><%= t('activerecord.attributes.category.name') %></th>
          <th scope="col"><%= t('activerecord.attributes.category.description') %></th>
          <th scope="col"><%= t('button_configure') %></th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <%= render category %>
        <% end %>
      </tbody>
    </table>
    <%= paginate @categories %>
  </div>

</div>

app/views/categories/new.html.erb
<h1><%= t('helpers.submit.create', :model => Category.model_name.human) %></h1>
<%= render "form", category: @category %>

<br>

<div>
  <%= link_to t('label_all') + ' ' + Category.model_name.human(:count => 2), categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal"><%= @category.name %></h1>
    </div>
  </div>
  <div class="row">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col"><%= t("activerecord.attributes.category.name") %></th>
          <th scope="col"><%= t("activerecord.attributes.category.description") %></th>
          <th scope="col"><%= t('button_configure') %></th>
        </tr>
      </thead>
      <tbody>
          <%= render @category %>
      </tbody>
    </table>
  </div>

</div>